// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnpwlvtiqrulxnqvupra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRucHdsdnRpcXJ1bHhucXZ1cHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzQ0MjksImV4cCI6MjA3MzUxMDQyOX0.NFyP9T9r4_G3dt_02hTZ4KXZ82nyxoh5wCvm0GfzlN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});